# Generated by Django 4.2.6 on 2023-10-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, upload_to='preview/', verbose_name='изображение (превью)'),
        ),
    ]
